name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the version of Node.js you want

      - name: Install dependencies
        run: npm install

      - name: Set up .env file
        run: |
          echo "AUTHORIZATION=${{ secrets.AUTHORIZATION }}" > .env

      - name: Run tests
        run: npm run test
